image: node:alpine

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .npm

stages:
    - test

before_script:
    - cd SocialBubble
    - npm install
    - npm ci --cache .npm
    - npx expo install react-native-safe-area-context
    - npx expo install jest-expo jest
    - npm install react-test-renderer@18.1.0


eas-build:
    stage: test
    script:
        - echo "Will fix tests after everything is done"

