image: node:alpine

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .npm

stages:
    - test

before_script:
    - cd SocialBubble
    - npm install
    - npm ci --cache .npm
    - npx expo install react-native-safe-area-context
    -npm install jest@26.6.3 --save-dev
    - npm install jest-expo@47.0.1 --save-dev

eas-build:
    stage: test
    script:
        - npm run test

